---
- hosts: all
  gather_facts: no
  vars:
    - osp_url: http://openstack.hattrick.lab:5000/v2.0
    - osp_project: operators
    - osp_user: operator
    - osp_pass: redhat
  tasks:
    - name: Create a unique ID
      shell: echo "`date +"%Y%m%d%H%M%S"`-$(cat /dev/urandom | tr -cd [:alpha:] | tr '[:upper:]' '[:lower:]' | head -c 4)"
      register: my_unique_id

    - name: Launch a RHEL instance to STIG
      os_server:
        auth:
          auth_url: "{{ osp_url }}"
          username: "{{ osp_user }}"
          password: "{{ osp_pass }}"
          project_name: "{{ osp_project }}"
        name: rhel-stig-{{ my_unique_id.stdout }}
        state: present
        key_name: operator
        availability_zone: nova
        nics:
          - net-name: private
        image: rhel75
        flavor: m1.small
        security_groups: default
        auto_ip: yes
      register: osp_host

    - name: wait for instance become ready to use
      wait_for:
       host: "{{ osp_host.openstack.public_v4 }}"
       port: "22"
       timeout: "320"
       state: "started"

    - name: Pause playbook execution for 30 seconds
      pause:
        seconds: 30

    - name: add new instance to inventory
      add_host:
        hostname: "{{ osp_host.openstack.public_v4 }}"
        ansible_ssh_user: cloud-user
        groupname: rhel-stig

- hosts: rhel-stig
  vars:
    - local_repo_url: http://192.168.0.7/repos/
  tasks:
    - name: enable the needed rhel repositories
      yum_repository:
        name: "{{ item }}"
        description: "{{ item }}"
        baseurl: "{{ local_repo_url }}{{ item }}"
        gpgcheck: no
        enabled: yes
        file: rhn-local
        state: present
      with_items:
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms

- hosts: rhel-stig
  become: yes
  vars:
    scap_reports_dir: /tmp
    scap_profile: stig-rhel7-disa
  roles:
    - rhtps.800-53
  tasks:
    - name: determine the most recent scap report
      command: ls -tr /tmp/scap_reports/
      register: results

    - name: install apache
      yum:
        name: httpd
        state: latest

    - name: enable service httpd and ensure it is not masked
      systemd:
        name: httpd
        enabled: yes
        masked: no

    - name: create the scap directory in the web server content
      file:
        name: /var/www/html/scap
        state: directory
        mode: 0755

    - name: copy SCAP reports to the web server content directory
      copy:
        remote_src: True
        src: "/tmp/scap_reports/{{ item }}"
        dest: /var/www/html/scap
        mode: 0644
      with_items: "{{ results.stdout_lines }}"
      when: item | match("scan-xccdf-report-*")
